### ISSUE TITLE
TSDiagram

### ISSUE THREAD

**Issue by 3rd** [xyflow/web#284]
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Project Name

TSDiagram

### Project Description

Create diagrams and plan your code with TypeScript.

### Project Tags

software development, data modeing, typescript

### Link to the project website

http://tsdiagram.com

### Link to project demo

http://tsdiagram.com

### Used Library

React Flow

### Upload a Project Screenshot

![image](https://github.com/xyflow/web/assets/59587503/21ab1664-ff25-40e1-8b82-873701c377ce)

### Additional Information

Thank you for your work, amazing library.

**Comment by johnrobbjr** [comment]
LGTM, added to showcase! https://github.com/xyflow/web/commit/10b6f9b03d8f04985ee297c1d23b0fcf37215e34

I did end up using a screenshot from the link you sent instead of the one you uploaded, because I think it demonstrates a more accurate use case- BUT I do love the easer egg in the screenshot 🐣

Thanks for submitting ☺️
